init:

  variables:
    SP6_LOG_NO_TIMESTAMPS: 1

  script: |
    set -e
    sudo apk add tree coreutils
    zef install --/test Tomty


main:
  build:
    pre: |
      set -e
      export SP6_DUMP_TASK_CODE=1
      zef install . --/test 2>&1
      tomty  --all --show-failed
